apiVersion: v1
kind: Service
metadata:
  name: kubernetes-frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort  # Change to LoadBalancer if on a cloud provider
  ports:
    - protocol: TCP
      port: 80             # Port exposed by the Service
      targetPort: 80       # Port on the container
      nodePort: 30001      # Optional: specify NodePort if desired
